# Generated by Django 5.2.7 on 2025-11-12 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yatra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('is_registration_open', models.BooleanField(default=True)),
                ('payment_upi_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YatraFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field name (e.g., accommodation)', max_length=100)),
                ('label', models.CharField(help_text='Label shown to user', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for select/radio (e.g., Dorm,Shared,Private)')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='yatra.yatra')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='YatraEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatra_approvals_given', to='userProfile.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatra_eligibilities', to='userProfile.profile')),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_approvals', to='yatra.yatra')),
            ],
            options={
                'verbose_name_plural': 'Yatra Eligibilities',
                'unique_together': {('yatra', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='YatraInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., Full Payment (₹6500)', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='yatra.yatra')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('yatra', 'label')},
            },
        ),
        migrations.CreateModel(
            name='YatraRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_made', to='userProfile.profile')),
                ('registered_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_received', to='userProfile.profile')),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yatra.yatra')),
            ],
            options={
                'unique_together': {('yatra', 'registered_for')},
            },
        ),
    ]
