# Generated by Django 5.2.7 on 2025-12-05 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yatra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('is_registration_open', models.BooleanField(default=True)),
                ('payment_upi_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YatraAccommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('checkin_datetime', models.DateTimeField()),
                ('checkout_datetime', models.DateTimeField()),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='yatra.yatra')),
            ],
            options={
                'ordering': ['checkin_datetime'],
            },
        ),
        migrations.CreateModel(
            name='YatraCustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Datetime'), ('choice', 'Choice'), ('file', 'File')], default='text', max_length=20)),
                ('is_multiple', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='yatra.yatra')),
            ],
            options={
                'ordering': ['order', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='YatraCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='yatra.yatracustomfield')),
            ],
            options={
                'verbose_name': 'Custom Field Value',
                'verbose_name_plural': 'Custom Field Values',
            },
        ),
        migrations.CreateModel(
            name='YatraFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field name (e.g., accommodation)', max_length=100)),
                ('label', models.CharField(help_text='Label shown to user', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for select/radio (e.g., Dorm,Shared,Private)')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='yatra.yatra')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='YatraJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('onward', 'Onward'), ('return', 'Return'), ('break', 'Break')], max_length=20)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('mode_of_travel', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='yatra.yatra')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='YatraInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., Full Payment (₹6500)', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='yatra.yatra')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('yatra', 'label')},
            },
        ),
    ]
