# Generated by Django 5.2.7 on 2025-12-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatra',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='yatra',
            name='substitution_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
