# Generated by Django 5.2.7 on 2025-11-12 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_delete_yatraregistrationinstallment'),
        ('userProfile', '0001_initial'),
        ('yatra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatraRegistrationInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yatra.yatrainstallment')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='payment.payment')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='yatra.yatraregistration')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_installments', to='userProfile.profile')),
            ],
            options={
                'unique_together': {('registration', 'installment')},
            },
        ),
    ]
