# Generated by Django 5.2.7 on 2025-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatra',
            name='is_rcs_download_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='yatra',
            name='is_substitution_open',
            field=models.BooleanField(default=True),
        ),
    ]
