# Generated by Django 5.2.7 on 2025-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0002_yatra_is_rcs_download_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatra',
            name='is_rcs_download_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='yatra',
            name='is_substitution_open',
            field=models.BooleanField(default=False),
        ),
    ]
