# Generated by Django 5.2.7 on 2025-11-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0002_yatraregistrationinstallment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatraregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('partial', 'Incomplete'), ('paid', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
