# Generated by Django 5.2.7 on 2025-12-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0003_alter_yatra_is_rcs_download_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatra',
            name='close_yatra',
            field=models.BooleanField(default=False),
        ),
    ]
