# Generated by Django 5.2.7 on 2026-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0004_yatra_close_yatra'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatra',
            name='accept_full_payment_only_date',
            field=models.DateField(blank=True, help_text='After this date, partial installment payment is not allowed for new registrations.', null=True),
        ),
        migrations.AddField(
            model_name='yatra',
            name='is_cancellation_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yatra',
            name='payment_refund_date',
            field=models.DateField(blank=True, help_text='Date after which refund for cancellations will be made.', null=True),
        ),
    ]
