# Generated by Django 5.2.7 on 2026-01-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0005_yatra_accept_full_payment_only_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatraImportantNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_in_rcs', models.BooleanField(default=True, help_text='If unchecked, this note will not appear in RCS')),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_notes', to='yatra.yatra')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='YatraContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Yatra Information & Help Desk, Medical Emergency', max_length=255)),
                ('numbers', models.TextField(blank=True, help_text='Comma-separated numbers (optionally with name, e.g., Dr. Ramesh:1234567890)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_in_rcs', models.BooleanField(default=True)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_categories', to='yatra.yatra')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('yatra', 'title')},
            },
        ),
    ]
