# Generated by Django 5.2.7 on 2026-06-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0006_yatraimportantnote_yatracontactcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_approval', models.BooleanField(default=True, help_text='If unchecked, the yatra is open to all — mentor approval step is skipped entirely.')),
                ('min_chanting_rounds', models.IntegerField(default=0, help_text='Minimum daily chanting rounds required to register. Set 0 to disable.')),
                ('yatra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_policy', to='yatra.yatra')),
            ],
        ),
    ]
