# Generated by Django 5.2.7 on 2026-06-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0007_registrationpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatra',
            name='poster',
            field=models.ImageField(blank=True, help_text='Poster image displayed on the yatra listing card.', null=True, upload_to='yatra/posters/'),
        ),
    ]
