# Generated by Django 5.2.7 on 2026-01-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announcements', '0001_initial'),
        ('yatra', '0006_yatraimportantnote_yatracontactcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='resource_thumbnails/')),
                ('category', models.CharField(choices=[('lecture', 'Lecture'), ('kirtan', 'Kirtan'), ('reading', 'Reading Material'), ('guideline', 'Guidelines'), ('instruction', 'Instructions'), ('other', 'Other')], default='other', max_length=30)),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('youtube', 'YouTube')], max_length=20)),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('mr', 'Marathi'), ('kn', 'Kannada')], max_length=10)),
                ('link_url', models.URLField(help_text='Google Drive / YouTube / External link')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='announcements.event')),
                ('yatra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='yatra.yatra')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
