# Generated by Django 5.2.7 on 2025-11-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_delete_yatraregistrationinstallment'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='verified_at',
            new_name='processed_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to='userProfile.profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review'), ('refunded', 'Refunded')], default='under_review', max_length=20),
        ),
    ]
