# Generated by Django 5.2.7 on 2025-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_verified_at_payment_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('under_review', 'Under Review'), ('refunded', 'Refunded')], default='under_review', max_length=20),
        ),
    ]
