# Generated by Django 5.2.7 on 2025-12-13 09:55

import django.db.models.deletion
import userProfile.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_id', models.PositiveIntegerField(editable=False, unique=True)),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('devotee', 'Devotee'), ('mentor', 'Mentor')], default='guest', max_length=20)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('sannyasi', 'Sannyasi'), ('grhastha', 'Grhastha'), ('others', 'Others'), ('unmarried', 'Unmarried'), ('vanaprastha', 'Vanaprastha'), ('brahmachari_temple', 'Brahmachari (Temple)')], max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhar_card_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('center', models.CharField(blank=True, max_length=150, null=True)),
                ('is_initiated', models.BooleanField(default=False)),
                ('initiated_name', models.CharField(blank=True, max_length=255, null=True)),
                ('spiritual_master', models.CharField(blank=True, max_length=255, null=True)),
                ('initiation_date', models.DateField(blank=True, null=True)),
                ('initiation_place', models.CharField(blank=True, max_length=255, null=True)),
                ('email_consent', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=userProfile.models.profile_picture_upload_path)),
                ('no_of_chanting_rounds', models.PositiveIntegerField(default=0, help_text='Number of daily chanting rounds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='userProfile.profile')),
                ('to_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='userProfile.profile')),
            ],
        ),
    ]
