# Generated by Django 5.2.7 on 2025-12-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
