# Generated by Django 5.2.7 on 2026-01-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_profile_member_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mentorrequest',
            index=models.Index(fields=['from_user', 'to_mentor', '-created_at'], name='mentorreq_from_to_created_idx'),
        ),
    ]
