# Generated by Django 5.2.7 on 2025-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('sannyasi', 'Sannyasi'), ('grhastha', 'Grhastha'), ('others', 'Others'), ('unmarried', 'Unmarried'), ('vanaprastha', 'Vanaprastha'), ('brahmachari_temple', 'Brahmachari (Temple)')], max_length=20, null=True),
        ),
    ]
