# Generated by Django 5.2.7 on 2026-06-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_mentorrequest_mentorreq_from_to_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_connected_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='iskcon_introduced_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='iskcon_introduction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
