# Generated by Django 5.2.7 on 2025-11-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_profile_profile_picture_alter_profile_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar_card_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='member_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('devotee', 'Devotee')], default='guest', max_length=20),
        ),
    ]
