# Generated by Django 5.2.7 on 2025-11-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_profile_aadhar_card_no_profile_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_id',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
