# Generated by Django 5.2.7 on 2025-11-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_alter_profile_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
