# Generated by Django 5.2.7 on 2025-11-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_alter_profile_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_id',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
