# Generated by Django 5.2.7 on 2025-11-06 12:51

import userProfile.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_alter_profile_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatra',
            name='is_registration_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=userProfile.models.profile_picture_upload_path),
        ),
        migrations.AlterField(
            model_name='yatra',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
