# Generated by Django 5.2.7 on 2025-11-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0010_yatra_is_registration_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_chanting_rounds',
            field=models.PositiveIntegerField(default=0, help_text='Number of daily chanting rounds'),
        ),
    ]
