# Generated by Django 5.2.7 on 2025-11-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_profile_no_of_chanting_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('devotee', 'Devotee'), ('mentor', 'Mentor')], default='guest', max_length=20),
        ),
    ]
