# Generated by Django 5.2.7 on 2025-11-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_alter_profile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='userProfile.profile')),
                ('to_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='userProfile.profile')),
            ],
        ),
    ]
