# Generated by Django 5.2.7 on 2025-11-07 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_alter_mentorrequest_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatraEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatra_approvals_given', to='userProfile.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatra_eligibilities', to='userProfile.profile')),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_approvals', to='userProfile.yatra')),
            ],
            options={
                'verbose_name_plural': 'Yatra Eligibilities',
                'unique_together': {('yatra', 'profile')},
            },
        ),
    ]
