# Generated by Django 5.2.7 on 2025-11-09 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0015_yatraeligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatraFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field name (e.g., accommodation)', max_length=100)),
                ('label', models.CharField(help_text='Label shown to user', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('select', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('date', 'Date')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for select/radio (e.g., Dorm,Shared,Private)')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='userProfile.yatra')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='YatraInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., Full Payment (₹6500)', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='userProfile.yatra')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('yatra', 'label')},
            },
        ),
    ]
