# Generated by Django 5.2.7 on 2026-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('event', 'Event — Full event with image, date & registration'), ('workshop', 'Workshop — Structured session with image & details'), ('announcement', 'Announcement — Short positive news (one-liner)'), ('notice', 'Notice — Administrative/important alert (one-liner)')], default='event', help_text='Controls how this item is displayed on the home page.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Keep to one line for Announcement / Notice categories.'),
        ),
    ]
