# Generated by Django 5.2.7 on 2025-12-13 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('userProfile', '0001_initial'),
        ('yatra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YatraRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Not Started'), ('partial', 'Incomplete'), ('paid', 'Confirmed'), ('substituted', 'Substituted '), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='pending', max_length=20)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substitution_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_made', to='userProfile.profile')),
                ('registered_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations_received', to='userProfile.profile')),
                ('substituted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_from', to='userProfile.profile')),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yatra.yatra')),
            ],
            options={
                'unique_together': {('yatra', 'registered_for')},
            },
        ),
        migrations.CreateModel(
            name='YatraEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatra_approvals_given', to='userProfile.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatra_eligibilities', to='userProfile.profile')),
                ('yatra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_approvals', to='yatra.yatra')),
            ],
            options={
                'verbose_name_plural': 'Yatra Eligibilities',
                'unique_together': {('yatra', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('seat_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yatra.yatrajourney')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_allocations', to='yatra_registration.yatraregistration')),
            ],
            options={
                'unique_together': {('registration', 'journey')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yatra.yatracustomfield')),
                ('custom_field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yatra.yatracustomfieldvalue')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='yatra_registration.yatraregistration')),
            ],
            options={
                'unique_together': {('registration', 'custom_field')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationAccommodation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bed_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yatra.yatraaccommodation')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_allocations', to='yatra_registration.yatraregistration')),
            ],
            options={
                'unique_together': {('registration', 'accommodation')},
            },
        ),
        migrations.CreateModel(
            name='YatraRegistrationInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yatra.yatrainstallment')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='payment.payment')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='yatra_registration.yatraregistration')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_installments', to='userProfile.profile')),
            ],
            options={
                'unique_together': {('registration', 'installment')},
            },
        ),
    ]
