# Generated by Django 5.2.7 on 2026-01-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_alter_profile_member_id'),
        ('yatra', '0004_yatra_close_yatra'),
        ('yatra_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='yatraregistration',
            index=models.Index(fields=['registered_at'], name='yatra_regis_registe_cb7d96_idx'),
        ),
        migrations.AddIndex(
            model_name='yatraregistration',
            index=models.Index(fields=['status'], name='yatra_regis_status_7b4a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='yatraregistration',
            index=models.Index(fields=['yatra'], name='yatra_regis_yatra_i_ff7fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='yatraregistration',
            index=models.Index(fields=['registered_for'], name='yatra_regis_registe_72457f_idx'),
        ),
    ]
