# Generated by Django 5.2.7 on 2025-12-08 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra', '0001_initial'),
        ('yatra_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationcustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yatra.yatracustomfield'),
        ),
        migrations.AlterUniqueTogether(
            name='registrationcustomfieldvalue',
            unique_together={('registration', 'custom_field')},
        ),
    ]
