# Generated by Django 5.2.7 on 2025-12-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
        ('yatra_registration', '0002_registrationcustomfieldvalue_custom_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatraregistration',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yatraregistration',
            name='substituted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_from', to='userProfile.profile'),
        ),
        migrations.AddField(
            model_name='yatraregistration',
            name='substitution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='yatraregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('partial', 'Incomplete'), ('paid', 'Confirmed'), ('substituted', 'Substituted '), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
