# Generated by Django 5.2.7 on 2026-01-19 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra_registration', '0002_yatraregistration_yatra_regis_registe_cb7d96_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCSDownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcs_download_events', to='yatra_registration.yatraregistration')),
            ],
            options={
                'indexes': [models.Index(fields=['registration'], name='yatra_regis_registr_58a88b_idx'), models.Index(fields=['created_at'], name='yatra_regis_created_ff6a53_idx')],
            },
        ),
    ]
