# Generated by Django 5.2.7 on 2026-01-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra_registration', '0003_rcsdownloadevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rcsdownloadevent',
            name='yatra_regis_created_ff6a53_idx',
        ),
        migrations.AddField(
            model_name='rcsdownloadevent',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rcsdownloadevent',
            name='last_downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rcsdownloadevent',
            name='timestamps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='rcsdownloadevent',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rcs_download_event', to='yatra_registration.yatraregistration'),
        ),
        migrations.AddIndex(
            model_name='rcsdownloadevent',
            index=models.Index(fields=['last_downloaded_at'], name='yatra_regis_last_do_57e90d_idx'),
        ),
    ]
