# Generated by Django 5.2.7 on 2025-12-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra_registration', '0003_yatraregistration_cancellation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatraregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Started'), ('partial', 'Incomplete'), ('paid', 'Confirmed'), ('substituted', 'Substituted '), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='pending', max_length=20),
        ),
    ]
