# Generated by Django 5.2.7 on 2025-12-13 09:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
        ('yatra_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstitutionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('two_digit_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_collected', models.BooleanField(default=False)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_sent', to='userProfile.profile')),
                ('new_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_reg', to='yatra_registration.yatraregistration')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.profile')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests', to='yatra_registration.yatraregistration')),
                ('target_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_received', to='userProfile.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['target_profile', 'status'], name='yatra_subst_target__a879dd_idx')],
            },
        ),
    ]
