# Generated by Django 5.2.7 on 2025-12-11 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatra_registration', '0004_alter_yatraregistration_status'),
        ('yatra_substitution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitutionrequest',
            name='fee_collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='substitutionrequest',
            name='new_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_reg', to='yatra_registration.yatraregistration'),
        ),
    ]
